version: '3'
services:
    db:
        image: postgres
        restart: always
        environment:
            POSTGRES_DB: personsdb
            POSTGRES_USER: jbadmin
            POSTGRES_PASSWORD: jbadmin
        ports:
            - "5432:5432"
        volumes:
            - ./database:/var/lib/postgresql